// Generated by gencs from handyman/PlaceConceptMsg.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;


namespace SIGVerse.ROSBridge 
{
	namespace CrestCamp
	{
		[System.Serializable]
		public class PlaceConceptMsg : ROSMessage
		{
			public double x;
			public double y;
			public double vx;
			public double vy;


			public PlaceConceptMsg()
			{
				this.x = 0.0;
				this.y = 0.0;
				this.vx = 0.0;
				this.vy = 0.0;
			}

			public PlaceConceptMsg(double x, double y, double vx, double vy)
			{
				this.x = x;
				this.y = y;
				this.vx = vx;
				this.vy = vy;
			}

			new public static string GetMessageType()
			{
				return "handyman/PlaceConceptMsg";
			}

			new public static string GetMD5Hash()
			{
				return "d181fc9f1eeb211fc87744356ce417a1";
			}
		} // class PlaceConceptMsg
	} // namespace handyman
} // namespace SIGVerse.ROSBridge

